### ISSUE TITLE
[Bug] 导出json文件后再导入，发布后微信扫码打开报错

### ISSUE THREAD

**Issue by scofier** [cloudtogo/pageplug#1]
## Description

![6321657010698_ pic](https://user-images.githubusercontent.com/306486/177288357-8ee74a3a-ad94-43e8-8a12-20b06da0e26a.jpg)

### Steps to reproduce the behaviour:

1. 导出为json之后，再导入，操作发布，生成小程序码，手机扫码，提示上面的错误

### Important Details

- Version: [Cloud ]
- OS: [MacOSX]
- Browser [edge]
- Environment [production]

**Comment by lifeneedspassion** [comment]
编辑器预览的时候没有这个问题吗？
能不能把json发给我试试
