### ISSUE TITLE
当进入app/client目录编译运行命令yarn build时出现下面错误,该怎么处理?

### ISSUE THREAD

**Issue by cnsdytzy** [cloudtogo/pageplug#10]
当进入app/client目录编译运行命令yarn build时出现下面错误,该怎么处理?
Module not found: Error: You attempted to import /home/my/pageplug/app/client/node_modules/@tarojs/taro-h5/dist/index.cjs.js which falls outside of the project src/ directory. Relative imports outside of src/ are not supported.
You can either move it inside src/, or add a symlink to it from project's node_modules/.

**Comment by tonychen0716** [comment]
同问.

@lifeneedspassion

**Comment by lifeneedspassion** [comment]
已修复
