### ISSUE TITLE
[Bug]: pageplug-open-v1.9.35 report error ，can't loading plugs when create new application . LOG INFO:  java.lang.NullPointerException: Cannot invoke "org.pf4j.PluginWrapper.getPluginClassLoader()" because the return value of "org.pf4j.PluginManager.getPlugin(String)" is null

### ISSUE THREAD

**Issue by thinkyoyo** [cloudtogo/pageplug#100]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

can't loading plugs when create new application

![image](https://github.com/user-attachments/assets/aa6e5e9e-9a01-493f-a483-42cc6e4edeba)

![image](https://github.com/user-attachments/assets/a647ebe9-b316-4668-92fb-62efaa93f958)

java.lang.NullPointerException: Cannot invoke "org.pf4j.PluginWrapper.getPluginClassLoader()" because the return value of "org.pf4j.PluginManager.getPlugin(String)" is null

### Steps To Reproduce

can't loading plugs when create new application

### Environment

Production

### Version

open-v1.9.35

**Comment by AppsmithCN** [comment]
确认下是不是按照官方文档通过git bash的方式启动的

**Comment by thinkyoyo** [comment]
thanks ，this problem has resolved.
rsync isn't work in in windows env
