### ISSUE TITLE
[Feature]: 在表格中添加按钮后，必须要先点击行内空白，Table1.selectedRow 才会是鼠标实际的行内容

### ISSUE THREAD

**Issue by 2622594863** [cloudtogo/pageplug#105]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

![33](https://github.com/user-attachments/assets/440eb356-e69e-4be8-8054-3b134c37e75c)
在表格中添加按钮后，必须要先点击行内空白，Table1.selectedRow 才会是鼠标实际的行内容

### Why should this be worked on?

在表格中添加按钮后，必须要先点击行内空白，Table1.selectedRow 才会是鼠标实际的行内容

**Comment by 2622594863** [comment]
我的操作是 先点击了第一行的空白位置，然后直接点击第六行的按钮，就会出现这种情况

**Comment by AppsmithCN** [comment]
1、没太理解你描述的内容，你可以说下期望效果；
2、{{Table1.selectedRow}}本身就是需要点击选中当前行后，才能正常获取对应的值；
3、lowcode.methodot的环境是在线体验环境，不建议存储数据信息在体验环境中，而且版本也很旧，建议私有化部署最新的版本

**Comment by 2622594863** [comment]
> 1、没太理解你描述的内容，你可以说下期望效果； 2、{{Table1.selectedRow}}本身就是需要点击选中当前行后，才能正常获取对应的值； 3、lowcode.methodot的环境是在线体验环境，不建议存储数据信息在体验环境中，而且版本也很旧，建议私有化部署最新的版本

我遇到的问题是 先点击第一行 然后直接点击第六行的按钮Table1.selectedRow的数据还是第一行的，请问有什么办法可以点击按钮就选择这行吗，可能我描述的有一些问题

**Comment by 2622594863** [comment]
> 1、没太理解你描述的内容，你可以说下期望效果； 2、{{Table1.selectedRow}}本身就是需要点击选中当前行后，才能正常获取对应的值； 3、lowcode.methodot的环境是在线体验环境，不建议存储数据信息在体验环境中，而且版本也很旧，建议私有化部署最新的版本

因为我觉得，要点击哪行按钮，还要先点击哪行的数据，有些麻烦了

**Comment by johnsnow20087349** [comment]
如果是要对行数据进行操作的话，推荐使用 `triggeredRow`

**Comment by 2622594863** [comment]
> 如果是要对行数据进行操作的话，推荐使用 `triggeredRow`

非常感谢您的回复，我以为只有selectedRow这一个获取当前行的函数，才知道还有triggeredRow这个函数，成功解决了我的问题，打扰您了
