### ISSUE TITLE
[Feature]: table 表格属性设置

### ISSUE THREAD

**Issue by johnsnow20087349** [cloudtogo/pageplug#106]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

在使用社区版的表格时，需要对表格的 loading、pageNo 这些属性进行手动控制，但是没有发现有对应的setter，请问下这些属性设置的功能是企业版才有的吗？

### Why should this be worked on?

功能开放

**Comment by AppsmithCN** [comment]
1、原生的table组件是不支持的，目前企业版新开了一个antd-table组件，会比原生的更好用些；也可以自行二开
