### ISSUE TITLE
[Bug]: 本地部署时前端少文件，没有../shared/build-shared-dep.js

### ISSUE THREAD

**Issue by lsiten** [cloudtogo/pageplug#107]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

# 版本
open-v1.9.37
# 问题
在本地yarn install时候报错
```
Error: Cannot find module '/code/pageplug-1.9.37/app/shared/build-shared-dep.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1140:15)
    at Module._load (node:internal/modules/cjs/loader:981:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v18.20.4
```

### Steps To Reproduce

yarn install

### Environment

Production

### Version

open-v1.9.37

**Comment by AppsmithCN** [comment]
估计你系统要改下脚本命令，可以自己试下将set CURRENT_SCOPE=client&&node ../shared/build-shared-dep.js改成CURRENT_SCOPE=client node ../shared/build-shared-dep.js
