### ISSUE TITLE
Iframe无法使用摄像头和麦克风

### ISSUE THREAD

**Issue by hillsonzhang** [cloudtogo/pageplug#11]
桌面应用的Iframe组件和移动应用的HTML组件，无法调用设备的摄像头和麦克风，Appsmith也曾出现过这种问题，在一次更新中已修复，Appsmith issue : https://github.com/appsmithorg/appsmith/issues/12924

**Comment by lifeneedspassion** [comment]
您使用的是pageplug1.7的代码吗？
appsmith最新代码我会实时同步，不过pageplug1.8的代码要等到官方1.8大版本结束后发布，见谅😅

**Comment by lifeneedspassion** [comment]
已升级
