### ISSUE TITLE
table表格总页数异常

### ISSUE THREAD

**Issue by 4373979** [cloudtogo/pageplug#16]
table表格总页数异常
![image](https://user-images.githubusercontent.com/58925909/223888953-5a824784-dfef-4016-b546-6107fc6fea37.png)
第四页正常
![image](https://user-images.githubusercontent.com/58925909/223888983-5c06d278-c811-4a33-94e4-4e4c8c6e8e11.png)
第五页就拿总记录数自己除以搜索到的行数了
然后下一页>按钮也可以按

**Comment by AppsmithCN** [comment]
已经修复，下个版本推送更新

**Comment by AppsmithCN** [comment]
版本已经推送修复，可更新使用
