### ISSUE TITLE
FORMILY表单内选择框内容不显示

### ISSUE THREAD

**Issue by 4373979** [cloudtogo/pageplug#17]
已配置
![image](https://user-images.githubusercontent.com/58925909/223889341-adce4e47-f78b-401f-b8ec-1526e8a95e67.png)
但不显示
![image](https://user-images.githubusercontent.com/58925909/223889313-fab1fcf0-b787-4f7a-a482-457960b29608.png)

**Comment by zsf1482451437** [comment]
![image](https://user-images.githubusercontent.com/62194517/236399474-11b27a32-f339-47b9-97a1-45924949f3da.png)
兄弟，你这样配置就可以了，value键名是硬性的，不能改
配置里面需要value这个键，类似于原生的下拉菜单，你需要给它label，界面上显示选项名称，但传给后端需要的是value
所以我们需要传label和value这两属性

in English：
Dude, you can do it like this, the value key name is hard, you can't change it you need the value key in the configuration, it's like the native drop-down menu, you need to give it label, it shows the option name on the screen, but you need to pass it to the back end it needs value so we need to pass label and value

**Comment by zsf1482451437** [comment]
![image](https://user-images.githubusercontent.com/62194517/236400658-1057cd41-e6e8-4914-ba5a-aba205c16b67.png)
补充

**Comment by AppsmithCN** [comment]
目前暂时无反馈，将关闭该issue。如果后续有问题，欢迎重新开启该issue来向社区反馈，
