### ISSUE TITLE
本地部署提示Module not found: Error: Can't resolve '@shared/ast'

### ISSUE THREAD

**Issue by ghost** [cloudtogo/pageplug#19]
本地开发部署运行时js报错

![image](https://user-images.githubusercontent.com/5507450/225830085-9595a10d-a2c0-482b-8176-d862985cfeb8.png)

安装完依赖运行就报错了

**Comment by AppsmithCN** [comment]
如果遇到@shared/ast找不到问题，其实就是本地包的之前，需要 yarn link 建立软链接

可以试下这样操作
`cd shared/ast 
yarn run link-package
cd client
yarn link @shared/ast`

详细的内容在安装教程里面有哈：[文档教程](https://appsmithcn.gitbook.io/appsmith-tutorial/xue-xi-wen-dang/bu-shu-an-zhuang/yuan-ma-ben-di-hua-bu-shu-windows-ban#4.1-qi-dong-ben-di-nginx-docker)

欢迎加入社区一同探研pageplug的多样场景开发
