### ISSUE TITLE
GraphQL提交中文数据乱码

### ISSUE THREAD

**Issue by zijin-zj** [cloudtogo/pageplug#20]
**🙋🏻‍♂️描述下你的问题**
在使用PagePlug是出现了什么问题
使用GraphQL提交数据导致中文乱码，使用Rest API就不会存在这种问题

**🧑🏻‍💻贴图**
可以在这里附上报错日志的截图及报错提醒内容，更好发现是什么内容导致
![image](https://user-images.githubusercontent.com/48403386/229492718-ecedbfe0-a6b3-4bbf-9cb5-ea31e8a029e8.png)
![image](https://user-images.githubusercontent.com/48403386/229493038-98dc99f9-e785-4914-85ac-cff1ecc3354e.png)

**🥳复现流程**
1⃣️ 使用了什么组件
不使用组件，直接使用graphql写死中文入参就会出现

2⃣️ 做了哪些相关的操作（连接API、写了某个属性值等等，越详细越好）

3⃣️ 尝试过如何处理
一开始以为是机器编码问题，查看了机器编码是 en_US.UTF-8，是支持中文了，而且Rest Api就没有这种问题。

**🤔想实现的效果**
可以描述下在设计开发的时候，预期想要达成的效果
graphql提交中文数据不乱码

**🔗PagePlug环境版本**
1⃣️ 本地化部署 — v1.9.10版本

**Comment by AppsmithCN** [comment]
收到反馈，

**Comment by AppsmithCN** [comment]
![image](https://github.com/cloudtogo/pageplug/assets/104495020/3a28133f-abde-458a-bdb4-4441ffe4cea2)

收到反馈，添加charset=UTF-8即可正常使用
