### ISSUE TITLE
JSON表单修改数据源字段之后，被修改的那条字段被添加到了表单的最后

### ISSUE THREAD

**Issue by dylansss** [cloudtogo/pageplug#21]
**🙋🏻‍♂️描述下你的问题**
JSON表单修改数据源字段之后，被修改的那条字段被添加到了表单的最后，包括配置项里
**🧑🏻‍💻贴图**
可以在这里附上报错日志的截图及报错提醒内容，更好发现是什么内容导致
![微信图片_20230424111859](https://user-images.githubusercontent.com/38618803/233892734-dc90f506-5f4b-4a02-b3a7-f5d5e5dc8a45.png)
![image](https://user-images.githubusercontent.com/38618803/233892801-05e1e848-0f43-4077-8db4-778b7ee7e01c.png)

**🥳复现流程**
1⃣️ JSON表单
2⃣️ 修改数据源
3⃣️ 源码debug但是没找到到底是在哪处理的
**🤔想实现的效果**
就按照JSON数据来解析

**🔗PagePlug环境版本**
1⃣️ 本地化部署 —1.7版本

**Comment by zsf1482451437** [comment]
![bf23dd4431297b4a8771e45c489ae32](https://user-images.githubusercontent.com/62194517/236200901-81fc92fc-2b5d-47a5-ba0a-ec6794816dc9.png)
兄弟，源码在这里了，我不太确定它是否修改了sourceData的属性顺序，咱们可以讨论下

**Comment by zsf1482451437** [comment]
config开始的路径在pageplug\app\client\src\widgets\JSONFormWidget

**Comment by zsf1482451437** [comment]
按我的理解，修改键名时，实际上是删除了原始键值对并添加了一个新的键值对，而添加新的键值对时，它们将会被添加到对象的末尾。类似这样的操作：
![image](https://user-images.githubusercontent.com/62194517/236592162-70e6cafc-57e3-491a-bded-ccc3c4bcf5af.png)
如果想改，可能要换成Map或Set，不用对象

**Comment by AppsmithCN** [comment]
有其他问题欢迎再次打开issue向社区反馈
