### ISSUE TITLE
表单组件内的文本不支持复制

### ISSUE THREAD

**Issue by AppsmithCN** [cloudtogo/pageplug#25]
**🙋🏻‍♂️描述下你的问题**
表单组件内的文本不支持复制，其他的支持支持

**🧑🏻‍💻贴图**
![image](https://user-images.githubusercontent.com/104495020/236453699-34f5037a-0cf8-45ca-adea-aa8df377e378.png)
![image](https://user-images.githubusercontent.com/104495020/236453931-4225b130-ec2c-43ed-bf22-13dcc7210599.png)

**🥳复现流程**
1⃣️ 表单组件
2⃣️ 做了哪些相关的操作（连接API、写了某个属性值等等，越详细越好）
3⃣️ 尝试过如何处理

**🤔想实现的效果**
可以将表单内的文本复制粘贴

**🔗PagePlug环境版本**
2⃣️ 私有化部署 —镜像V1.9.10

**Comment by ariallyp** [comment]
是的，表格里面的字段都不支持复制，要复制一个设备ID都用不了，不知道为什么会出现这样的问题。

**Comment by AppsmithCN** [comment]
新版1.9.20推送已支持文本复制的功能，可自行更新，有问题可以重新打开这个issue
