### ISSUE TITLE
使用docker方式部署老报错： Error loading templates metadata in plugin

### ISSUE THREAD

**Issue by Lee-Flier** [cloudtogo/pageplug#29]
**🙋🏻‍♂️描述下你的问题**
使用docker方式部署老报错： Error loading templates metadata in plugin

**🧑🏻‍💻问题日志**
pageplug  | backend stdout | [2023-05-18 04:10:52,480] userEmail=test@pageplug.com, sessionId=b5a3cac3-6999-4961-9b94-e6a7155179d7, thread=nioEventLoopGroup-3-6, requestId=0a057034-8405-49f5-b3b6-07a5670720b5 - Error loading templates metadata in plugin restapi-plugin
pageplug  | backend stdout |
pageplug  | backend stdout | [2023-05-18 04:10:52,504] userEmail=test@pageplug.com, sessionId=b5a3cac3-6999-4961-9b94-e6a7155179d7, thread=nioEventLoopGroup-3-3, requestId=0a057034-8405-49f5-b3b6-07a5670720b5 - Error loading templates metadata in plugin elasticsearch-plugin
pageplug  | backend stdout |
pageplug  | backend stdout | [2023-05-18 04:10:52,505] userEmail=test@pageplug.com, sessionId=b5a3cac3-6999-4961-9b94-e6a7155179d7, thread=nioEventLoopGroup-3-3, requestId=0a057034-8405-49f5-b3b6-07a5670720b5 - Error loading templates metadata in plugin dynamo-plugin
pageplug  | backend stdout |
导致创建应用一直编辑不了，编辑页面加载失败

**🔗PagePlug环境版本**
2⃣️ 私有化部署 —v1.9.10版本

**Comment by AppsmithCN** [comment]
1、麻烦复现下报错的流程，没报错之前你是做了什么操作，

2、看着问题像是在pageplug里面导入json后，报的错

**Comment by Lee-Flier** [comment]
@AppsmithCN 就docker-compose up -d启动服务以后，网页进入服务，创建用户后默认创建一个app时，加载页面失败，查后台日志，就是报的上面的错误

**Comment by AppsmithCN** [comment]
我刚复现了下没有问题唉，之前有没有拉过pageplug的镜像，拉过的话，yml文件里面改下镜像的名称，重新拉下看看

**Comment by AppsmithCN** [comment]
有其他问题欢迎再次打开issue向社区反馈
