### ISSUE TITLE
热更新很慢，而且是整个页面刷新

### ISSUE THREAD

**Issue by helloann** [cloudtogo/pageplug#30]
yarn start-win启动项目，但是热更新很慢，修改个字符串都能编译好久。
而且编译好了，是整个页面刷新，有办法解决么？

**Comment by AppsmithCN** [comment]
这个我们先记一下吧，是不是电脑内存不够？编译也确实会比较久一点

**Comment by AppsmithCN** [comment]
这个我们先记一下吧，是不是电脑内存不够？内存不够编译也确实会比较久一点

**Comment by helloann** [comment]
感谢回复。我的电脑是16gb。应该是够的。一个是慢，另一个是编译后，整个页面是全部刷新，不是局部刷新的

**Comment by AppsmithCN** [comment]
有其他问题欢迎再次打开issue向社区反馈
