### ISSUE TITLE
自定义表格如何进行行内编辑，保存当前的一条数据，需要示例

### ISSUE THREAD

**Issue by Moicechul** [cloudtogo/pageplug#37]
**🙋🏻‍♂️描述下你的问题**
在使用PagePlug是出现了什么问题
不知道自定义表格行内编辑如何保存当前的一条数据，需要示例

**🧑🏻‍💻贴图**
<img width="788" alt="image" src="https://github.com/cloudtogo/pageplug/assets/104495020/346d25e9-10fa-489b-a2cb-a4f23adf554a">

**🥳复现流程**
1⃣️ 使用了什么组件
自定义表格
2⃣️ 做了哪些相关的操作（连接API、写了某个属性值等等，越详细越好）
3⃣️ 尝试过如何处理

**🤔想实现的效果**

需要示例

**🔗PagePlug环境版本**
1⃣️ 本地化部署 —xxx版本
2⃣️ 私有化部署 —xxx版本
3⃣️ 在线体验环境

**Comment by AppsmithCN** [comment]
1、表单数据用global来处理
2、保存事件绑定一个js函数
3、借助global可以对表单数据进行增加

![image](https://github.com/cloudtogo/pageplug/assets/104495020/b5f674f2-4b8e-417d-aa4c-d9834b47070b)
![image](https://github.com/cloudtogo/pageplug/assets/104495020/5dbd312b-2f34-46cd-b7bd-931703a2b26d)
![image](https://github.com/cloudtogo/pageplug/assets/104495020/b167af9e-256c-4695-81ea-ceef077ef361)
![image](https://github.com/cloudtogo/pageplug/assets/104495020/22f039c1-95dc-4d93-93dd-219f91009a9c)

**Comment by AppsmithCN** [comment]
有其他问题欢迎再次打开issue向社区反馈
