### ISSUE TITLE
更换外部MongoDB后启动报错

### ISSUE THREAD

**Issue by rteqd** [cloudtogo/pageplug#38]
**🙋🏻‍♂️描述下你的问题**
更换外部MongoDB后启动报错，并且之前创建的帐户提示密码错误

**🧑🏻‍💻贴图**

![截图](https://github.com/cloudtogo/pageplug/assets/136149607/3dc1114a-00e2-4396-b991-50dda58c7012)

**🥳复现流程**
一、按文档部署docker镜像
二、正常进入pageplug创建管理员帐号后进入管理员设置
三、将高级配置中的MongoDB URI更改为mongodb://host.docker.internal:27017/appsmith，保存并重启服务（MongoDB版本为5.0.18）
四、直接报错/能够成功创建数据库，但重启docker后启动报错
五、尝试先建立MongoDB用户，赋予用户数据库权限为readWrite，报错。
尝试在URI后添加?retryWrites=true&authSource=admin，报错。
在.env文件中配置对应的数据库帐户密码，报错。

**🤔想实现的效果**
一、能够登陆开始时创建的pageplug管理员帐户
二、更换外部MongoDB

**🔗PagePlug环境版本**
2⃣️ 私有化部署 —docker 1.9.10版本

**Comment by AppsmithCN** [comment]
可以看下这里，mongo的切换需要按照MongoDB官方文档中的步骤将副本集升级到5.0

如果配置没成功的话，我们后面出个案例吧
https://docs.appsmith.com/getting-started/setup/instance-configuration/custom-mongodb-redis#docusaurus_skipToContent_fallback

**Comment by AppsmithCN** [comment]
该issue将被关闭，如有其他问题，欢迎再次打开issue向社区反馈
