### ISSUE TITLE
菜单栏挤压导致右侧画布自适应失效

### ISSUE THREAD

**Issue by yizhijiaozi** [cloudtogo/pageplug#42]
**🙋🏻‍♂️描述下你的问题**
RT，更新1.9.20版本后使用了新的菜单栏，出现了现有画布被挤压，自适应未生效的情况

**🧑🏻‍💻贴图**
配置页面
<img width="1026" alt="image" src="https://github.com/cloudtogo/pageplug/assets/53572746/1aa2a992-0739-4b40-b8cb-11d779baa11a">
最终发布后显示的页面（自适应的情况下不应该出现横向滚动条）
<img width="1264" alt="image" src="https://github.com/cloudtogo/pageplug/assets/53572746/6daf83a3-1a6e-43ab-9973-3d574e0b3f65">

**🔗PagePlug环境版本**
2⃣️ 私有化部署 —1.9.20版本

**Comment by AppsmithCN** [comment]
问题已记录，本周会推送一个修复版

**Comment by AppsmithCN** [comment]
已修复更新，可重新下载拉取使用，有问题可随时提交反馈～～
