### ISSUE TITLE
docker服务pageplug连接本地的postgresql数据库

### ISSUE THREAD

**Issue by xiedaolin2000** [cloudtogo/pageplug#44]
**🙋🏻‍♂️描述下你的问题**
ubuntu22.04 使用docker安装pageplug，然后本地安装了postgres，根据文档说明，我怎么都连接不到本地的postgresql数据库；
然后测试安装原始的原始appsmithdocker版本，也是一样问题；

**🧑🏻‍💻贴图**
Failed to initialize pool: Connection to host.docker.internal:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.

**Comment by AppsmithCN** [comment]
使用的版本是？

**Comment by AppsmithCN** [comment]
host那里用host.docker.internal吧，看下PP的文档
https://docs.pageplug.cn/xue-xi-wen-dang/bu-shu-an-zhuang/tong-guo-ben-di-zhu-ji-lian-jie

**Comment by xiedaolin2000** [comment]
> 

使用 docker-compose.yaml 拉取的版本

就是 按照 PP的文档；使用host.docker.internal ，一直都不行，所以来咨询下；

**Comment by xiedaolin2000** [comment]
原来是postgresql 配置文件里面的listen没有配置正确，已经解决了
