### ISSUE TITLE
pageplug1.9.20 表格数据当页最后一行数据 被翻页工具 遮挡

### ISSUE THREAD

**Issue by mark-hooo** [cloudtogo/pageplug#47]
**🙋🏻‍♂️描述下你的问题**
pageplug1.9.20 表格数据当页最后一行数据, 被翻页工具 遮挡，无法显示

**🧑🏻‍💻贴图**
![image](https://github.com/cloudtogo/pageplug/assets/132184501/c58cf3b7-ed90-47f8-bd8c-e48c323734bd)
![image](https://github.com/cloudtogo/pageplug/assets/132184501/1244f161-596d-4918-a6f9-b0e74b49e02f)

**🥳复现流程**
1⃣️ 使用表格组件

**🤔想实现的效果**
正确显示最后一行数据

**🔗PagePlug环境版本**
1⃣️ 本地化部署 —1.9.20版本

**Comment by AppsmithCN** [comment]
已知问题，下一个版本会优化

**Comment by AppsmithCN** [comment]
最新的1.9.35版本已修复该问题，可更新最新的镜像版本，源码也将在近期推送更新，留意社区消息推送
