### ISSUE TITLE
创建新的应用组无法删除，退出会报错

### ISSUE THREAD

**Issue by lcsin** [cloudtogo/pageplug#5]
我创建新的应用组后，想删除该应用组，点击退出应用按钮后会报错：The last admin can not be removed from an organization
![image](https://user-images.githubusercontent.com/49903755/185070556-48e9e0d1-9c44-45f5-9733-7b1135e77b58.png)

**Comment by lifeneedspassion** [comment]
版本升级后就不会有这个问题了 😁
