### ISSUE TITLE
点击列表项上的文本组件时，onItemClick事件无法被触发

### ISSUE THREAD

**Issue by huanghaiyang** [cloudtogo/pageplug#51]
![image](https://github.com/cloudtogo/pageplug/assets/5448818/b2294231-85c3-4cc4-89b0-95c174847d57)
![image](https://github.com/cloudtogo/pageplug/assets/5448818/33d2c41a-0719-4ca8-af81-28e611b619e5)

**Comment by AppsmithCN** [comment]
没看懂你js里面的那个是哪来的，你想实现什么样的效果
