### ISSUE TITLE
How to connect use Oracle services ?

### ISSUE THREAD

**Issue by 328950225** [cloudtogo/pageplug#52]
**🙋🏻‍♂️描述下你的问题**
在使用PagePlug是出现了什么问题

**🧑🏻‍💻贴图**
可以在这里附上报错日志的截图及报错提醒内容，更好发现是什么内容导致

**🥳复现流程**
1⃣️ 使用了什么组件
2⃣️ 做了哪些相关的操作（连接API、写了某个属性值等等，越详细越好）
3⃣️ 尝试过如何处理

**🤔想实现的效果**
可以描述下在设计开发的时候，预期想要达成的效果

**🔗PagePlug环境版本**
1⃣️ 本地化部署 —xxx版本
2⃣️ 私有化部署 —xxx版本
3⃣️ 在线体验环境

**Comment by AppsmithCN** [comment]
Firstly, what version of PagePlug are you currently using? What is the version of Oracle?
