### ISSUE TITLE
1.9.20版本的最新代码在哪里下载？目前同步下来的代码编译以后发现还是1.8.15版本的

### ISSUE THREAD

**Issue by frank-dkvan** [cloudtogo/pageplug#56]
**🙋🏻‍♂️描述下你的问题**
1.9.20版本的最新代码在哪里下载？目前同步下来的代码编译以后发现还是1.8.15版本的

**🧑🏻‍💻贴图**
可以在这里附上报错日志的截图及报错提醒内容，更好发现是什么内容导致

**🥳复现流程**
下载open-1.8分支上的最新代码编译运行，即可发现功能和代码的最新版本仍是1.18.15

**🤔想实现的效果**
希望能在GitHub及时下载同步到最新版本的代码

**Comment by AppsmithCN** [comment]
下个版本是1.9.35，在下个版本的镜像更新后同步推送源码

**Comment by frank-dkvan** [comment]
> 下个版本是1.9.35，在下个版本的镜像更新后同步推送源码

请问下个版本什么时间发布？
