### ISSUE TITLE
弹窗组件重命名后，右上角自带的x按钮功能失效

### ISSUE THREAD

**Issue by beiweixiaohuo** [cloudtogo/pageplug#57]
**🙋🏻‍♂️描述下你的问题**
弹窗组件重命名后，右上角自带的x按钮功能失效，修改后最初默认名时可关闭弹窗

**🧑🏻‍💻贴图**
![image](https://github.com/cloudtogo/pageplug/assets/40163692/e80b5eb4-e021-404b-b17e-d7f3317d264f)
![image](https://github.com/cloudtogo/pageplug/assets/40163692/4ea6601b-5bf3-4db4-9804-5522bf1bfdd8)

**🥳复现流程**
1⃣️ 弹窗组件
2⃣️ 修改组件名

**🤔想实现的效果**
修改组件名后，右上角 x 按钮可用

**🔗PagePlug环境版本**
在线体验环境

**Comment by AppsmithCN** [comment]
在线体验环境是v1.8.15的，可以自行查看下[PagePlug私有化部署](https://docs.pageplug.cn/%E5%AD%A6%E4%B9%A0%E6%96%87%E6%A1%A3/%E9%83%A8%E7%BD%B2%E5%AE%89%E8%A3%85/%E7%A7%81%E6%9C%89%E5%8C%96%E9%83%A8%E7%BD%B2-%E5%90%ABdocker%E5%AE%89%E8%A3%85%E6%95%99%E7%A8%8B)的教程，目前最新的是1.9.20，10月底会发1.9.35的版本，也会同步更新在线体验环境

**Comment by beiweixiaohuo** [comment]
> 在线体验环境是v1.8.15的，可以自行查看下[PagePlug私有化部署](https://docs.pageplug.cn/%E5%AD%A6%E4%B9%A0%E6%96%87%E6%A1%A3/%E9%83%A8%E7%BD%B2%E5%AE%89%E8%A3%85/%E7%A7%81%E6%9C%89%E5%8C%96%E9%83%A8%E7%BD%B2-%E5%90%ABdocker%E5%AE%89%E8%A3%85%E6%95%99%E7%A8%8B)的教程，目前最新的是1.9.20，10月底会发1.9.35的版本，也会同步更新在线体验环境

本地部署的1.9.20也是有这个问题

**Comment by AppsmithCN** [comment]
他不是bug，是因为modal弹窗的关闭默认配置的弹窗名称是modal1，所以如果你更改了弹窗的名称后，在iconbutton这里，更新下弹窗名称即可
<img width="1469" alt="image" src="https://github.com/cloudtogo/pageplug/assets/104495020/5919b000-5ec4-4b9c-a14d-7ee7a521ed6b">

**Comment by beiweixiaohuo** [comment]
在V1.8.15的这里修改了也关不掉，V1.9.20的可以
