### ISSUE TITLE
源码本地部署，按文档步骤都成功了，怎么启动不行

### ISSUE THREAD

**Issue by beiweixiaohuo** [cloudtogo/pageplug#60]
**🙋🏻‍♂️描述下你的问题**
源码本地部署，按文档步骤都成功了，怎么启动不行

**🧑🏻‍💻贴图**
![image](https://github.com/cloudtogo/pageplug/assets/40163692/fc3cfda6-c55e-40a1-83fc-e37cb2934b78)
![image](https://github.com/cloudtogo/pageplug/assets/40163692/1e0c4eff-656a-404b-b7ce-889204920a7d)

**🥳复现流程**
这个Nginx启动正确吗

**🤔想实现的效果**
成功启动项目

**🔗PagePlug环境版本**
本地源码部署

**Comment by AppsmithCN** [comment]
访问下127.0.0.1是否成功，检查下你机器的host映射关系是否正确配置

**Comment by beiweixiaohuo** [comment]
> 访问下127.0.0.1是否成功，检查下你机器的host映射关系是否正确配置

![image](https://github.com/cloudtogo/pageplug/assets/40163692/7a6b7ee9-82b1-49b6-b37f-e3c6b47f5497)
有配置host的，127.0.0.1访问不了

**Comment by beiweixiaohuo** [comment]
找到原因了，是刚安装的一个软件把**端口占用了**，难怪之前用着的本地docker私有化的也用不了了
