### ISSUE TITLE
docker部署找不到logger.js

### ISSUE THREAD

**Issue by oohy** [cloudtogo/pageplug#63]
![Uploading 1698825599315.jpg…]()

**Comment by AppsmithCN** [comment]
看不到图片

**Comment by oohy** [comment]
![1698825599315](https://github.com/cloudtogo/pageplug/assets/21984631/65992a44-e913-4069-9291-df85d55ec988)

**Comment by AppsmithCN** [comment]
看看你docker的日志目录权限是不是不足,会导致logger.js无法正确写入日志文件,从而报错。另外一个可能是docker时区的问题，你排查下这两块的内容看下
