### ISSUE TITLE
JSON表单修改显示字段名后，有时有些字段会变回去

### ISSUE THREAD

**Issue by beiweixiaohuo** [cloudtogo/pageplug#66]
**🙋🏻‍♂️描述下你的问题**
JSON表单修改显示字段名后，有时有些字段会变回去

**🧑🏻‍💻贴图**
![image](https://github.com/cloudtogo/pageplug/assets/40163692/efe6d331-89f3-4c55-9406-c8fa9dffba18)

**🥳复现流程**
1⃣️ JSON表单
2⃣️ 修改显示的字段名

3⃣️ 尝试过如何处理
未修改其中字段名，不清楚什么时候会出现这个bug，不是一直会，有遇到两三次这种情况

**🤔想实现的效果**

**🔗PagePlug环境版本**
1⃣️ 本地化部署 —v1.9.20吧？10月份安装的

**Comment by AppsmithCN** [comment]
你的数据查询是不是重新请求或者是有其他更新的，所以出现了这样的情况。其他社区同学有处理的方式是，将字段做了处理之后再渲染到表单上
