### ISSUE TITLE
导航栏能否自定义功能，查询/JS 能否实现不同页面共用

### ISSUE THREAD

**Issue by beiweixiaohuo** [cloudtogo/pageplug#67]
**🙋🏻‍♂️描述下你的问题**
1、导航栏（下图红框区）能否自定义功能，如个人信息、设置、退出等
2、查询/JS 能否实现不同页面共用

**🧑🏻‍💻贴图**
![image](https://github.com/cloudtogo/pageplug/assets/40163692/66626724-1d39-4cb5-8ca1-9ddf941ae1f2)

**🥳复现流程**

**🤔想实现的效果**
自定义导航栏功能、查询/JS 能实现不同页面共用

**🔗PagePlug环境版本**
1⃣️ 本地化部署 
2⃣️ 私有化部署 
3⃣️ 在线体验环境

**Comment by AppsmithCN** [comment]
新的版本支持个人中心用户，本周更新新的版本即可；查询/JS共用，这个会在下下个企业版中上线
