### ISSUE TITLE
怎么动态设置按钮显示text

### ISSUE THREAD

**Issue by beiweixiaohuo** [cloudtogo/pageplug#68]
**🙋🏻‍♂️描述下你的问题**
在PagePlug怎么动态设置按钮text和是否可用，
在appsmith中有setLabel、setDisabled 方法，pageplug中好像不能用

**🧑🏻‍💻贴图**
![image](https://github.com/cloudtogo/pageplug/assets/40163692/d37776ef-5893-4f2d-a428-770833b7886b)

**🥳复现流程**
1⃣️ 普通按钮组件

**🤔想实现的效果**
想实现发送验证码功能，点击进行倒计时并且按钮不可再点击，倒计时结束可重新发送

**🔗PagePlug环境版本**
1⃣️ 本地化部署

**Comment by AppsmithCN** [comment]
这个在本周1.9.35的版本中就会有支持了，到时候更新版本即可

**Comment by beiweixiaohuo** [comment]
> 这个在本周1.9.35的版本中就会有支持了，到时候更新版本即可

你好，本地部署v1.8.5 的支持吗？v1.8.5 怎么更新？
