### ISSUE TITLE
Echart组件自定义图表无法使用

### ISSUE THREAD

**Issue by beiweixiaohuo** [cloudtogo/pageplug#70]
**🙋🏻‍♂️描述下你的问题**
Echart组件自定义图表无法使用

**🧑🏻‍💻贴图**
![image](https://github.com/cloudtogo/pageplug/assets/40163692/7ef28e94-ea02-40fe-85ba-e95355aa985b)
![image](https://github.com/cloudtogo/pageplug/assets/40163692/4100382d-004a-4cdc-8f1a-8479de3e0446)

**🥳复现流程**
1⃣️ Echart组件

**🤔想实现的效果**

**🔗PagePlug环境版本**
1⃣️ 本地化部署 
3⃣️ 在线体验环境

**Comment by AppsmithCN** [comment]
格式错了，知乎上有一个案例教学，可以看下demo

https://www.zhihu.com/question/40710074/answer/3278938981
