### ISSUE TITLE
docker 私有部署如何关闭注册或者存在管理员界面来控制权限

### ISSUE THREAD

**Issue by LZC6244** [cloudtogo/pageplug#73]
**🙋🏻‍♂️描述下你的问题**
docker 私有部署如何关闭注册或者存在管理员界面来控制权限

**🧑🏻‍💻贴图**
可以在这里附上报错日志的截图及报错提醒内容，更好发现是什么内容导致

**🥳复现流程**
1⃣️ 使用了什么组件
2⃣️ 做了哪些相关的操作（连接API、写了某个属性值等等，越详细越好）
3⃣️ 尝试过如何处理

**🤔想实现的效果**
注册、权限可控

**🔗PagePlug环境版本**
1⃣️ 本地化部署 —xxx版本
2⃣️ 私有化部署 —xxx版本
3⃣️ 在线体验环境

**Comment by AppsmithCN** [comment]
注册可以直接在管理员设置中【身份认证】中的账号密码登陆配置中修改，如果要配置【管理员设置】的权限和入口的话，在docker部署的话看下/stacks/configuration/docker.env里面的APPSMITH_ADMIN_EMAILS，配置这个就可以了

**Comment by LZC6244** [comment]
> 注册可以直接在管理员设置中【身份认证】中的账号密码登陆配置中修改，如果要配置【管理员设置】的权限和入口的话，在docker部署的话看下/stacks/configuration/docker.env里面的APPSMITH_ADMIN_EMAILS，配置这个就可以了

可以了 感谢 ～ 🌹
