### ISSUE TITLE
v1.9.35 导航栏菜单内容为空

### ISSUE THREAD

**Issue by beiweixiaohuo** [cloudtogo/pageplug#74]
**🙋🏻‍♂️描述下你的问题**
v1.9.35 导航栏菜单内容为空

**🧑🏻‍💻贴图**
![image](https://github.com/cloudtogo/pageplug/assets/40163692/2efe0a7d-cd6b-40ea-adc5-3367906739b6)
![image](https://github.com/cloudtogo/pageplug/assets/40163692/929d2eaa-5f28-4dcb-947c-aff8f0d42fd6)

**🥳复现流程**

**🤔想实现的效果**

**🔗PagePlug环境版本**
2⃣️ 私有化部署 —v1.9.35 版本

**Comment by AppsmithCN** [comment]
导航功能做了重构，所以你需要重新配置下导航菜单即可

**Comment by beiweixiaohuo** [comment]
> 导航功能做了重构，所以你需要重新配置下导航菜单即可

是旧版本导出再导入新版本的，保存了也无效呢。新建项目是正常的
