### ISSUE TITLE
导航栏菜单无法设置图标

### ISSUE THREAD

**Issue by beiweixiaohuo** [cloudtogo/pageplug#75]
**🙋🏻‍♂️描述下你的问题**
导航栏菜单无法设置图标，新增目录倒是可以设置图标

**🧑🏻‍💻贴图**
![image](https://github.com/cloudtogo/pageplug/assets/40163692/6ba6dafe-cf43-47dd-b1ab-75a24144b93e)

**🥳复现流程**
设计项目菜单

**🤔想实现的效果**

**🔗PagePlug环境版本**
2⃣️ 私有化部署 —v1.9.35 版本

**Comment by AppsmithCN** [comment]
页面配置图标的意义是？我们认为层级菜单对图标的需求会更多些
