### ISSUE TITLE
管理员设置入口如何进入？

### ISSUE THREAD

**Issue by kl2101** [cloudtogo/pageplug#76]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

在本地docker中部署的pageplug，可以进入管理员配置页面。

在sealos.io中配置的界面，无管理员配置界面。

### Steps To Reproduce

通过sealos.io部署的，镜像名为：cloudtogouser/pageplug-ce

![20231204_1416Google Chrome应用管理 - PagePlug](https://github.com/cloudtogo/pageplug/assets/66360035/f11c9224-3961-4c85-8a5f-62628f4386c2)

### Environment

Release

### Version

cloudtogouser/pageplug-ce

**Comment by AppsmithCN** [comment]
部署起来的时候，应该会有一个引导配置，引导配置填写的那个邮箱及密码，就是管理员账号；另外一种新增配置，docker部署的话可以配置下APPSMITH_ADMIN_EMAILS这个变量

**Comment by kl2101** [comment]
> 部署起来的时候，应该会有一个引导配置，引导配置填写的那个邮箱及密码，就是管理员账号；另外一种新增配置，docker部署的话可以配置下APPSMITH_ADMIN_EMAILS这个变量

感谢回复，我现在的账号就是引导配置时的账号，但是进去没有管理员界面的入口。或者管理员界面是否有固定的域名后缀？

**Comment by AppsmithCN** [comment]
后缀可以加/settings

**Comment by kl2101** [comment]
> 后缀可以加/settings

当我使用链接：https://my-domain/settings ，但是会直接跳转到 https://my-domain/applications。

当前登录的账号是最开始配置的我的admin账号。

**Comment by AppsmithCN** [comment]
没法定位你的原因，是从这个页面进去之后填写的邮箱信息不

![image](https://github.com/cloudtogo/pageplug/assets/104495020/b1cda621-e936-4ae2-a84a-07e1fb60eaf6)

或者要不你重新run个新的镜像，如果已经有开发的应用，可以先把应用导出为json，后续再导入进去

**Comment by AppsmithCN** [comment]
也推荐使用最新的1.9.35的版本，功能会更强大一些

**Comment by kl2101** [comment]
> 也推荐使用最新的1.9.35的版本，功能会更强大一些

收到，感谢。
1. 是你刚才的界面进入的；
2. 1.9.35是否有[docker公共](https://hub.docker.com/)的版本上的版本？

**Comment by AppsmithCN** [comment]
有的，你可以直接从dockerhub上拉取，也可以看看PagePlug文档https://docs.pageplug.cn/%E5%AD%A6%E4%B9%A0%E6%96%87%E6%A1%A3/%E9%83%A8%E7%BD%B2%E5%AE%89%E8%A3%85/%E7%A7%81%E6%9C%89%E5%8C%96%E9%83%A8%E7%BD%B2-%E5%90%ABdocker%E5%AE%89%E8%A3%85%E6%95%99%E7%A8%8B
