### ISSUE TITLE
[Bug]: 私有化部署后，发布小程序，无预览二维码，疑似 app_id 被写死

### ISSUE THREAD

**Issue by 18sby** [cloudtogo/pageplug#77]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

按照这份文档部署到 Mac 本地的：https://docs.pageplug.cn/%E5%AD%A6%E4%B9%A0%E6%96%87%E6%A1%A3/%E9%83%A8%E7%BD%B2%E5%AE%89%E8%A3%85/%E7%A7%81%E6%9C%89%E5%8C%96%E9%83%A8%E7%BD%B2-%E5%90%ABdocker%E5%AE%89%E8%A3%85%E6%95%99%E7%A8%8B/#2mac-%E7%89%88

问题素材：
![image](https://github.com/cloudtogo/pageplug/assets/47735184/400a6450-f96b-4505-bce2-3e6f8b4ccdda)
![image](https://github.com/cloudtogo/pageplug/assets/47735184/e7539eac-af37-43cf-9b1d-c2c8d7089783)

### Steps To Reproduce

1. 创建小程序应用
2. 创建页面
3. 拖拽 List 组件到页面
4. 点击右侧面板的「绑定数据」按钮
5. 在弹出的数据源页面，选择 users 表的「生成新页面」按钮
6. 在弹出的快速向导页面，选择数据源、table、search column 后，点击「GENERATE PAGE」按钮
7. 点击发布应用，然后在访问页面就是如上 Description 中的截图状况了，小程序二维码获取失败，是否可以有一个修改小程序 app_id 的方式

### Environment

Production

### Version

不知道如何查看版本，2023.12.28 按照文档，部署的 Mac 版本到本机

**Comment by AppsmithCN** [comment]
1、在应用组中的左下角可以看到版本
2、小程序配置在左下角的管理员设置中，小程序选项里面可以配置ID和密钥
3、如果要生成二维码，需要本地跑源码，把小程序打成dist包在微信平台过审，后续PP上发布修改会同步过去，具体的可以看看PP文档,docs.pageplug.cn

**Comment by 18sby** [comment]
感谢解答，我用的是 v1.9.10 版本，文档上面本地启动的部分我看了，小程序 ID 和密钥在 PP 上配置了，想要部署小程序的话，需要把 git 仓库拉下，本地启动，开发，然后导出小程序代码么？

我是不是可以在私有化部署的 PP 上，导出我搭建的小程序应用为 json 文件，然后在拉代码本地启动的 PP 上导进来，然后导出小程序代码去部署就可以啦？

**Comment by 18sby** [comment]
> 1、在应用组中的左下角可以看到版本 2、小程序配置在左下角的管理员设置中，小程序选项里面可以配置ID和密钥 3、如果要生成二维码，需要本地跑源码，把小程序打成dist包在微信平台过审，后续PP上发布修改会同步过去，具体的可以看看PP文档,docs.pageplug.cn

感谢解答，我用的是 v1.9.10 版本，文档上面本地启动的部分我看了，小程序 ID 和密钥在 PP 上配置了，想要部署小程序的话，需要把 git 仓库拉下，本地启动，开发，然后导出小程序代码么？

我是不是可以在私有化部署的 PP 上，导出我搭建的小程序应用为 json 文件，然后在拉代码本地启动的 PP 上导进来，然后导出小程序代码去部署就可以啦？

**Comment by AppsmithCN** [comment]
你开发好的应用json文件可以在本地中导入，最后自己打dist包

**Comment by 18sby** [comment]
> 你开发好的应用json文件可以在本地中导入，最后自己打dist包

好，感谢
