### ISSUE TITLE
ES连接报错

### ISSUE THREAD

**Issue by XiepengLi** [cloudtogo/pageplug#8]
## Description
创建 ES连接报错

`class [Ljava.lang.Object; cannot be cast to class [Lorg.apache.http.Header; ([Ljava.lang.Object; is in module java.base of loader 'bootstrap'; [Lorg.apache.http.Header; is in unnamed module of loader org.pf4j.PluginClassLoader @7c6189d5)`

**Comment by cnsdytzy** [comment]
当进入app/client目录编译运行命令yarn build时出现下面错误,该怎么处理?
Module not found: Error: You attempted to import /home/my/pageplug/app/client/node_modules/@tarojs/taro-h5/dist/index.cjs.js which falls outside of the project src/ directory. Relative imports outside of src/ are not supported.
You can either move it inside src/, or add a symlink to it from project's node_modules/.

**Comment by lifeneedspassion** [comment]
请尽量提供详细的复现步骤哈
