### ISSUE TITLE
QPermissionGroup缺失

### ISSUE THREAD

**Issue by huanyue6660** [cloudtogo/pageplug#80]
com.appsmith.server.domains.QPermissionGroup
实体类缺失

**Comment by huanyue6660** [comment]
111

**Comment by AppsmithCN** [comment]
Q类是通过命令生成的，q类生成之前可以先运行这个./build.sh -DskipTests

**Comment by a232433508** [comment]
源码里面要怎么处理？sh文件只能在linux上面使用的吧？本地是windows环境
