### ISSUE TITLE
不支持Custom Widgets组件吗？

### ISSUE THREAD

**Issue by nengc** [cloudtogo/pageplug#84]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

没有找到Custom Widgets组件，appsmith里面有
![image](https://github.com/cloudtogo/pageplug/assets/19792047/46e56e85-2472-4fbb-9f68-c696cd4034a3)

### Steps To Reproduce

没有找到Custom Widgets组件

### Environment

Production

### Version

ce-v1.9.35

**Comment by AppsmithCN** [comment]
这个后面社区版更新后支持，目前最新的是1.9.35版本，等社区版后面更新推送
