### ISSUE TITLE
[Bug]: 表格数据偶现无法展示，刷新后恢复

### ISSUE THREAD

**Issue by AndySpf** [cloudtogo/pageplug#87]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

你好，我遇到的问题如图：
表格绑定数据源后，偶现进入页面表格无数据，但是execute接口是正常返回了数据且表格下方的数量统计正确。然后再次刷新页面恢复正常。请问该如何解决？
![image](https://github.com/cloudtogo/pageplug/assets/33141719/9dbcff06-60de-4e7a-9b1b-46047ad5a7e3)

### Steps To Reproduce

1. 添加table组件
2. 绑定api
3. 发布后多个页面反复点击或者返回查看

### Environment

Production

### Version

image: 1.9.35

**Comment by AppsmithCN** [comment]
Table是不是之前已经绑定过一次数据查询呢，拖入一个新的Table组件绑定看看；另外一个，用的什么浏览器

**Comment by AndySpf** [comment]
感谢，按照这个操作后这两周没再出现过。我使用的chrome浏览器
还有个问题想请教一下，有表格的页面总是先加载出来表格，空白几秒后才加载出来数据，有没有什么方法可以优化一下？
