### ISSUE TITLE
[部署]：本地部署时，通过IDEA运行，报错程序包***不存在

### ISSUE THREAD

**Issue by bourne-3** [cloudtogo/pageplug#89]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

电脑环境是macos，源码版本为 1.9.35
通过idea运行 出现大量报错程序文件不存在
<img width="1421" alt="image" src="https://github.com/cloudtogo/pageplug/assets/59307069/7c2f915a-8ebf-4f6b-8b00-777af1b51354">

例如，这里的QUser，在 com.appsmith.server.domains 此路径没有对应的文件
<img width="1223" alt="image" src="https://github.com/cloudtogo/pageplug/assets/59307069/2e2c82ac-ee56-4dd7-a26a-18eb277a416d">

还有其他类也是这样，请问是为什么 如何解决

### Steps To Reproduce

1、拉取代码
2、按照 https://github.com/cloudtogo/pageplug/blob/open-v1.9.35/contributions/ServerSetup.md 指令进行安装
3、全部执行完毕，IDEA也配置完毕了

### Environment

Deploy Preview

### Version

1.9.35

**Comment by AppsmithCN** [comment]
1、这个有类似的回复，你可以检索下issue；Q类是通过命令生成的，q类生成之前可以先运行这个./build.sh -DskipTests

**Comment by AppsmithCN** [comment]
2、PagePlug有对应的文档内容，可以查看docs.pageplug.cn
