### ISSUE TITLE
pageplug连接redis集群

### ISSUE THREAD

**Issue by daymax-byte** [cloudtogo/pageplug#96]
🙋🏻‍♂️描述下你的问题
目前想使用pageplug本地化部署后连接redis集群，查看RedisConfig文件后发现redis-cluster应该只支持亚马逊的ElasticCache Redis的配置节点以及普通的单节点。
目前应该是没有对普通的redis集群做支持吗？如果想做支持是否需要自己修改RedisConfig类下的RedisURL读取方式即可。
🧑🏻‍💻贴图
<img width="951" alt="image" src="https://github.com/cloudtogo/pageplug/assets/67035780/c33018c4-f4b9-496a-b217-d785a57814b8">

🔗PagePlug环境版本
1⃣️ 本地化部署 —1.9.35版本

**Comment by AppsmithCN** [comment]
对的，如果是其他的可能需要自己改造下
