### ISSUE TITLE
[部署]内网Linux系统部署后端应用

### ISSUE THREAD

**Issue by daymax-byte** [cloudtogo/pageplug#97]
🙋🏻‍♂️描述下你的问题
在与外网隔离内网环境下的linux机器上进行本地部署时，在启动后端时出现了下面的错误

🧑🏻‍💻贴图
<img width="1152" alt="image" src="https://github.com/cloudtogo/pageplug/assets/67035780/5361f7e6-bfe4-473a-81fe-6ca96352446e">

<img width="1139" alt="image" src="https://github.com/cloudtogo/pageplug/assets/67035780/ebf112d1-8134-48ec-acf3-8c9d7139b01a">

🥳复现流程
1⃣️
# 启动 java 服务 
./scripts/start-dev-server.sh
在使用脚本启动java服务时出现了上述的问题。显示无法解析release-cs.appsmith.com name or service not known的问题。

2️⃣查看代码后发现是在.env文件夹下有APP_SMITH_CLOUD_SERVICES_BASE_URL的环境变量
<img width="637" alt="image" src="https://github.com/cloudtogo/pageplug/assets/67035780/151f3d1b-2109-4671-8a23-a0e0ff7ad800">
3️⃣在将APP_SMITH_CLOUD_SERVICES_BASE_URL修改为注释的localhost:8090后仍出现类似的问题
<img width="1142" alt="image" src="https://github.com/cloudtogo/pageplug/assets/67035780/947de5ae-09a0-43f0-8695-963b5b7a36ee">

🤔想实现的效果
在内网部署无法访问外网，是要再部署什么服务吗

🔗PagePlug环境版本
1⃣️ 内网本地化部署 —1.9.35版本

**Comment by AppsmithCN** [comment]
这是调用外网的一个模版服务，内网部署的话，可以把APP_SMITH_CLOUD_SERVICES_BASE_URL变量配置成内网任意可以访问的一个地址10.xxx，重新run就好了

**Comment by daymax-byte** [comment]
> 这是调用外网的一个模版服务，内网部署的话，可以把APP_SMITH_CLOUD_SERVICES_BASE_URL变量配置成内网任意可以访问的一个地址10.xxx，重新run就好了

已经将APP_SMITH_CLOUD_SERVICES_BASE_URL配置为了内网可访问的地址，但是出现了以下的问题：
image
发现还是需要通过地址调用接口，因此出现了404的问题。请问有办法可以绕过该调用吗，或者在代码里把哪块注释掉。
目前后端服务应该是没启起来的
