### ISSUE TITLE
[bug]formality组件无法获取到formdata信息

### ISSUE THREAD

**Issue by daymax-byte** [cloudtogo/pageplug#98]
🙋🏻‍♂️描述下你的问题
在1.9.35版本下使用formality组件时获取到的formData信息为空。在之前使用1.9.20版本时formality组件可以获取到formData信息。请问是1.9.35版本对formality组件进行了改动吗

🧑🏻‍💻贴图
<img width="798" alt="image" src="https://github.com/cloudtogo/pageplug/assets/67035780/b7c4326b-27b7-483d-b930-146472affdee">

🥳复现流程
1⃣️如图所示，formality组件属性的信息无法从formData获取显示为空，而只能通过formality下的metaData字段中的formData获取。
2️⃣但是metaData字段在SQL和JS调试时会显示无法解析
<img width="558" alt="image" src="https://github.com/cloudtogo/pageplug/assets/67035780/eee9bdc4-c621-4010-90ba-73f7f1231d7d">
进一步导致调试时不便。
<img width="1171" alt="image" src="https://github.com/cloudtogo/pageplug/assets/67035780/8a1fe688-59c4-4f4d-97e5-e3be17be22ec">

🤔想实现的效果
formality获取formData信息

🔗PagePlug环境版本
1⃣️ 1.9.35版本

**Comment by foooag** [comment]
+1

**Comment by foooag** [comment]
暂时使用 {{JSON.stringify(formily1.meta.formData)}} 救急了

**Comment by AppsmithCN** [comment]
ce-v1.9.37已修复
